name       : kplotting
version    : 5.96.0
release    : 61
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.96/kplotting-5.96.0.tar.xz : 090e3b25fd2bfcb37f5a9369163460300a57eef705198dae8decb79181111dfb
homepage   : https://community.kde.org/Frameworks
license    :
    - GPL-2.0.or-later
    - LGPL-2.0-or-later
component  : desktop.library
summary    : Data plotting
description: |
    KPlotting provides KPlotWidget, a QWidget-derived class that provides a virtual base class for easy data-plotting. The idea behind KPlotWidget is that you only have to specify information in "data units"; i.e., the natural units of the data being plotted. KPlotWidget automatically converts everything to screen pixel units.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Designer)
    - extra-cmake-modules
rundeps    :
    - devel :
        - extra-cmake-modules
        - qt5-tools-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
