name       : kplotting
version    : 5.71.0
release    : 38
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.71/kplotting-5.71.0.tar.xz : 84bacfbd86105e454f3d97f4ac4062e2f992556fca66d2c73806d1d12095bec1
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : desktop.library
optimize   : lto
summary    : Data plotting
description: |
    KPlotting provides KPlotWidget, a QWidget-derived class that provides a virtual base class for easy data-plotting. The idea behind KPlotWidget is that you only have to specify information in "data units"; i.e., the natural units of the data being plotted. KPlotWidget automatically converts everything to screen pixel units.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
