name       : kplotting
version    : 5.77.0
release    : 43
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.77/kplotting-5.77.0.tar.xz : 32226573989c105d84a324174d31a1ed4c7cbf57a75341873cd8fe5692d7a2e8
homepage   : https://community.kde.org/Frameworks
license    :
    - GPL-2.0.or-later
    - LGPL-2.0-or-later
component  : desktop.library
optimize   : lto
summary    : Data plotting
description: |
    KPlotting provides KPlotWidget, a QWidget-derived class that provides a virtual base class for easy data-plotting. The idea behind KPlotWidget is that you only have to specify information in "data units"; i.e., the natural units of the data being plotted. KPlotWidget automatically converts everything to screen pixel units.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
