name       : kplotting
version    : 5.35.0
release    : 3
source     :
    - https://download.kde.org/stable/frameworks/5.35/kplotting-5.35.0.tar.xz : bcfe144508e83a152f974ce85c64f3e375b9a0917cb01c2c0f7b2ffacfbcf671
license    : LGPL-2.1
component  : desktop.library
summary    : Data plotting
description: |
    KPlotting provides KPlotWidget, a QWidget-derived class that provides a virtual base class for easy data-plotting. The idea behind KPlotWidget is that you only have to specify information in "data units"; i.e., the natural units of the data being plotted. KPlotWidget automatically converts everything to screen pixel units.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
