name       : kplotting
version    : 5.41.0
release    : 8
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.41/kplotting-5.41.0.tar.xz : 3f4829a530e144a6d7ccef3e4ee4aa7ed952be08118c6a8a44a8ac844715f6a4
license    : LGPL-2.1
component  : desktop.library
optimize   : lto
summary    : Data plotting
description: |
    KPlotting provides KPlotWidget, a QWidget-derived class that provides a virtual base class for easy data-plotting. The idea behind KPlotWidget is that you only have to specify information in "data units"; i.e., the natural units of the data being plotted. KPlotWidget automatically converts everything to screen pixel units.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
setup      : |
    %cmake -DBUILD_QCH=ON .
build      : |
    %make
install    : |
    %make_install
