name       : kplotting
version    : 5.57.0
release    : 24
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.57/kplotting-5.57.0.tar.xz : c2c35030b1a2ca25f503c1a2df7ca225d156a9ea80f52883e136679aea6efc8e
license    : LGPL-2.1-or-later
component  : desktop.library
optimize   : lto
summary    : Data plotting
description: |
    KPlotting provides KPlotWidget, a QWidget-derived class that provides a virtual base class for easy data-plotting. The idea behind KPlotWidget is that you only have to specify information in "data units"; i.e., the natural units of the data being plotted. KPlotWidget automatically converts everything to screen pixel units.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
