name       : kplotting
version    : 5.61.0
release    : 28
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.61/kplotting-5.61.0.tar.xz : 95781b50bef0e081e48b472b4fcbbcd3301ec45245498261e4a3ec8e42b892ba
license    : LGPL-2.1-or-later
component  : desktop.library
optimize   : lto
summary    : Data plotting
description: |
    KPlotting provides KPlotWidget, a QWidget-derived class that provides a virtual base class for easy data-plotting. The idea behind KPlotWidget is that you only have to specify information in "data units"; i.e., the natural units of the data being plotted. KPlotWidget automatically converts everything to screen pixel units.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
